import Head from 'next/head'
import { Button, Col, Container, Form, Modal, Row, Table } from 'react-bootstrap'
import { useState } from 'react'




export default function Home({ users }) {
  
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const [data, setData] = useState({
    name: "",
    image: ""
  });

  const [validated, setValidated] = useState(false);

  const handleSubmit = (event) => {
    event.preventDefault();
    const form = event.currentTarget;
    if (form.checkValidity() === false) {
      event.preventDefault();
      event.stopPropagation();
    } else {
      handleUpload()
    }

    setValidated(true);
  };

  const handleUpload = () => {
    var formdata = new FormData();
    formdata.append("name", data.name);
    formdata.append("image", data.image);

    var requestOptions = {
      method: 'POST',
      body: formdata,
      redirect: 'follow'
    };

    fetch("/api/upload", requestOptions)
      .then(response => response.json())
      .then(result => {
        if(result.status === "success"){
          window.location.reload()
        }
        alert(result.msg)
      })
      .catch(error => console.log('error', error));
  }
  return (
    <>
      <Head>
        <title>S3 Upload</title>
        <meta name="description" content="Generated by S3 Upload" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Container>
          <Button className='float-end my-3' onClick={handleShow}>Add User </Button>
          <Table striped bordered hover>
            <thead>
              <tr>
                <th>#</th>
                <th>First Name</th>
                <th>Last Name</th>
              </tr>
            </thead>
            <tbody>
              {users && users.data && users.data.map((item, index) =>
                < tr key={index}>
                  <td>{index + 1}</td>
                  <td>{item.name}</td>
                  <td>
                    <img src={"http://localhost:3001/api/assets/" + item.image} alt={item.name} height={200} width={200} />
                  </td>
                </tr>
              )}

            </tbody>
          </Table>

          <Modal show={show} onHide={handleClose} centered>
            <Modal.Header closeButton>
              <Modal.Title>Add User</Modal.Title>
            </Modal.Header>
            <Modal.Body>
              <Form noValidate validated={validated} onSubmit={handleSubmit}>
                <Form.Group className="mb-3" controlId="formBasicName">
                  <Form.Label>Name</Form.Label>
                  <Form.Control
                    type="text"
                    placeholder="Enter name"
                    required
                    value={data.name}
                    onChange={(e) => setData(prevState => ({
                      ...prevState,
                      name: e.target.value
                    }))}
                  />
                </Form.Group>
                <Form.Group controlId="formFile" className="mb-3">
                  <Form.Label>Upload Image</Form.Label>
                  <Form.Control
                    type="file"
                    required
                    onChange={(e) => setData(prevState => ({
                      ...prevState,
                      image: e.target.files[0]
                    }))}
                  />
                </Form.Group>

                <Row className='mt-4'>
                  <Col className='text-end'>
                    <Button variant="outline-danger" type="button">
                      Cancel
                    </Button>
                  </Col>
                  <Col>
                    <Button variant="outline-success" type="submit">
                      Submit
                    </Button>
                  </Col>
                </Row>
              </Form>
            </Modal.Body>
          </Modal>
        </Container>
      </main>
    </>
  )
}


export async function getServerSideProps() {

  var requestOptions = {
    method: 'POST',
    redirect: 'follow'
  };
  const res = await fetch(`http://localhost:3001/api/users`, requestOptions)
  const data = await res.json()

  return { props: { users: data } }
}
